### PR TITLE
v1.2.1_admin_fac <Fund. templates of Create Faculty Hub> (2024.05.01, 23:32)

### PR DESCRIPTION
**Pull request by jelwingeuan**
-added templates for create_faculty_hub in both app.py & admin.html 
-of cuz 100% not working yet, but still cooking...

### CODE REVIEW

**Comment by jelwingeuan** [comment]
@kimhongzhang323 , i've added template in admin.html (line 76-90), see if anything you want to improve on (of cuz u wanna change cuz the is just words blocked by side nav bar lmao :p)

**Review by YangYiYap — APPROVED** [review]
it's cool, but next time can change the jsonify to flask module, like message or flash. According to jax said 
jax

**Comment by jelwingeuan** [comment]
> it's cool, but next time can change the jsonify to flask module, like message or flash. According to jax said jax

**Comment by jelwingeuan** [comment]
> it's cool, but next time can change the jsonify to flask module, like message or flash. According to jax said jax


alrightie, will change on next pull req

**Review by kimhongzhang323 — APPROVED** [review]

**Pull request merged**
